# Generated by Django 3.2.5 on 2021-08-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210828_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productview',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
