# Generated by Django 3.2.5 on 2021-08-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210828_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='username',
        ),
    ]
